<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>Boiler.GodotSmoke</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ThatRatDev.Steam.Boiler" Version="0.4.0" />
  </ItemGroup>
</Project>
