<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Boiler.Smoke</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ThatRatDev.Steam.Boiler" Version="0.4.0" />
  </ItemGroup>

</Project>
